// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"portfolio-backend/app/handler"
	"portfolio-backend/infra/repository"
)

// Injectors from wire.go:

func NewApp() (*App, error) {
	db, err := ProvideDB()
	if err != nil {
		return nil, err
	}
	rssFeedRepository := repository.NewRSSFeedRepository(db)
	postRSSFeedsHandler := handler.NewPostRSSFeedsHandler(rssFeedRepository)
	app := &App{
		PostRSSFeedsHandler: postRSSFeedsHandler,
	}
	return app, nil
}
