// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"portfolio-backend/app/handler"
	"portfolio-backend/infra/repository"
)

// Injectors from wire.go:

func NewApp() (*App, error) {
	db, err := repository.NewDB()
	if err != nil {
		return nil, err
	}
	rssFeedRepository := repository.NewRSSFeedRepository(db)
	rssFeedHandler := handler.NewRSSFeedHandler(rssFeedRepository)
	blogRepository := repository.NewBlogRepository(db)
	blogHandler := handler.NewBlogHandler(blogRepository)
	app := &App{
		RSSFeedHandler: rssFeedHandler,
		BlogHandler:    blogHandler,
	}
	return app, nil
}
