// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	BlogFromManualItems string
	BlogFromRSSItems    string
	RSSFeeds            string
	SchemaMigrations    string
}{
	BlogFromManualItems: "blog_from_manual_items",
	BlogFromRSSItems:    "blog_from_rss_items",
	RSSFeeds:            "rss_feeds",
	SchemaMigrations:    "schema_migrations",
}
